name: UltimatePlugin
version: '1.2'
author: BlackPoison357
main: io.github.xBlackPoison357x.UltimatePlugin.UltimatePlugin
api-version: 1.16
api: '1.16'
commands:
  recipegui:
    description: Opens the custom recipes GUI
    usage: /customrecipes
    aliases:
    - gui
    - customrecipes
  admingui:
    description: Opens the admin GUI
    usage: /admingui
    aliases:
    - gui
    - customrecipes  
  recipeload:
    description: Loads custom recipes
    usage: /recipeload
  Website:
    description: Displays your Website link.
    aliases:
      - infowebsite
  Donate:
    description: Displays donation link.
    aliases:
      - infodonate
  Vote:
    description: Displays voting link.
    aliases:
      - infovote
  Staff:
    description: Displays staff.
    aliases:
      - infostaff
  Rules:
    description: Displays rules.
    aliases:
      - inforules
  Serverinfo:
    description: Displays Server hardware stats.
    aliases:
      - infoserver
      - ram
  Motd:
    description: Displays Motd.
    aliases:
      - infomotd
  Online:
    description: Displays online players.
    aliases:
      - infoonline
  Ip:
    description: Displays Server Ip.
    aliases:
      - infoip
  Player:
    description: Displays player info.
    aliases:
      - infoplayer
  Twitter:
    description: Displays twitter link.
    aliases:
      - infotwitter
  Facebook:
    description: Displays facebook link.
    aliases:
      - infofacebook
  Einfo:
    description: Displays Extra Information about the server.
    aliases:
      - info
  Youtube:
    description: Displays youtube link.
    aliases:
      - infoyoutube
  Stats:
    description: Displays Stats about the server.
    aliases:
      - infostats
  Enchantall:
    description: Enchants an item fully.
    aliases:
      - enchant
  Uuid:
    description: Gets a player's UUID.
    aliases:
      - infouuid
  Ultimateupdate:
    description: manually checks for an update.
    aliases:
      - uupdate
  disablecommands:
    description: >-
      Allows addition, listing, and removing commands from the forbidden
      commands list.
    usage: >
      /disablecommands - Shows the help menu

      /disablecommands add <command> - Adds to the disabled commands list (Don't
      add /)

      /disablecommands remove <command> - Removes a command from the disabled
      commands list.

      /disablecommands list - Lists all the disabled commands.
permissions:
  ultimate.update:
    default: false
  information.*:
    description: Gives access to all information commands
    Permissionchildren:
      information.website: true
      information.donate: true
      information.vote: true
      information.staff: true
      information.rules: true
      information.serverinfo: true
      information.online: true
      information.ip: true
      information.player: true
      information.twitter: true
      information.facebook: true
      information.extra: true
      information.youtube: true
      information.stats: true
      information.creativebypass.world: true
      information.creativebypass.nether: true
      information.creativebypass.end: true
      information.joinbypass.world: true
      information.joinbypass.nether: true
      information.joinbypass.end: true
      information.uuid: true
      information.netherbuild.notify: true
      information.netherbuildbypass: true
      information.starterkit: true
      information.bossmessage: true
  information.member:
    description: Gives access to member commands
    Permissionchildren:
      information.website: true
      information.donate: true
      information.vote: true
      information.staff: true
      information.serverinfo: false
      information.online: false
      information.ip: true
      information.player: false
      information.twitter: true
      information.facebook: true
      information.extra: true
      information.youtube: true
      information.stats: false
      information.creativebypass.world: false
      information.creativebypass.nether: false
      information.creativebypass.end: false
      information.joinbypass.world: false
      information.joinbypass.nether: false
      information.joinbypass.end: false
      information.uuid: false
      information.netherbuild.notify: true
      information.netherbuildbypass: false
      information.starterkit: false
      information.bossmessage: true
  information.admin:
    description: Gives access to admin commands
    Permissionchildren:
      information.website: true
      information.donate: true
      information.vote: true
      information.staff: true
      information.rules: true
      information.serverinfo: true
      information.online: true
      information.ip: true
      information.player: true
      information.twitter: true
      information.facebook: true
      information.extra: true
      information.youtube: true
      information.stats: true
      information.flightbypass.world: true
      information.flightbypass.nether: true
      information.flightbypass.end: true
      information.creativebypass.world: true
      information.creativebypass.nether: true
      information.creativebypass.end: true
      information.joinbypass.world: true
      information.joinbypass.nether: true
      information.joinbypass.end: true
      information.uuid: true
      information.netherbuild.notify: true
      information.netherbuildbypass: true
      information.starterkit: true
      information.safezoneflight: true
      information.enemyflight: true
      information.neutralflight: true
      information.allyflight: true
      information.truceflight: true
      information.warzoneflight: true
      information.wildernessflight: true
      information.nosafezonedamage: true
      information.bossmessage: true
  frame.*:
    description: Gives all permissions.
    Permissionchildren:
      frame.remove: true
      frame.place: true
      frame.item.remove: true
      frame.rotate: true
      frame.bypass: true
  disablecommands.*:
    description: Gives all permissions to do with DisableCommands
    Permissionchildren: null
    disablecommands.bypass: true
    disablecommands.add: true
    disablecommands.remove: true
    disablecommands.list: true
  disablecommands.bypass:
    description: Bypasses command blocker
    default: false
  disablecommands.add:
    description: Adds to the disabled commands list
    default: false
  disablecommands.remove:
    description: Removes from the disabled commands list
    default: false
  disablecommands.list:
    description: Lists all the disabled commands
    default: false
  recipe.gui:
    description: Gives permission to the /recipegui command.
    default: false
  admin.gui:
    description: Gives permission to the /admingui command.
    default: false  
  recipe.load:
    description: Gives permission to the /recipeload command.
    default: false